name: Cmake CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        compiler: ["g++", "clang++"]
        os: ["ubuntu-16.04", "ubuntu-18.04"]
      
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: packegs
      run:  sudo apt install -y build-essential clang-6.0 autoconf automake bison expect libevent-dev libmysqlclient-dev libpcre3-dev libpq-dev libsqlite3-dev libssl-dev libtool libz-dev telnet libgtest-dev libjemalloc-dev
    - name: cmake
      env:
        CXX: ${{ matrix.compiler }}
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cd build && make
    - name: make test
      run: cd build && make test
